AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AI Photo Album Lambda CD
Resources:
  Hw3UploadToS3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3-upload-to-s3
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda/hw3-upload-to-s3.py
      Description: 'Lambda function for Uploading to S3'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::910222472548:role/service-role/AWSCodePipelineServiceRole-us-east-1-hw3-CodePipeline-P1'
      Policies: AmazonS3FullAccess
      Events:
        HttpPut:
          Type: Api
          Properties:
            Path: /upload
            Method: put
      Environment:
        Variables:
          REGION: us-east-1